using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace auto_generrated_id_i_textbox_from_database_table
{
    public partial class Employee_Registration_form : System.Web.UI.Page
    {
        string eno = "eno_";
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["Emp"].ConnectionString);

        protected void Page_Load(object sender, EventArgs e)
        {
            if (IsPostBack == false)
            {
                AutoGeneratedId();
            }


        }

        private void AutoGeneratedId()
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("select  count(*) from emp", con);
            int i = Convert.ToInt32(cmd.ExecuteScalar());
            con.Close();
            i++;
            eno = eno + i;
            txtEmpno.Text = eno;
        }

        protected void btnRegister_Click(object sender, EventArgs e)
        {
            con.Open();
            SqlCommand cmd = new SqlCommand("insert into emp values(@eno,@ename,@sal)",con);
            cmd.Parameters.AddWithValue("@eno", txtEmpno.Text);
            cmd.Parameters.AddWithValue("@ename", txtEname.Text);
            cmd.Parameters.AddWithValue("@sal", int.Parse(txtSalary.Text));
            cmd.ExecuteNonQuery();
            con.Close();
            AutoGeneratedId();
            txtEname.Text = "";
            txtSalary.Text = "";
        }
    }
}